from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm


def generate_pdf_report(incident, output_path):

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm
    )

    elements = []

    # Title
    elements.append(
        Paragraph(
            "SentinelAI Security Incident Report",
            title_style
        )
    )

    elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(
            "Explainable and Adaptive SIEM",
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # Incident information
    elements.append(
        Paragraph(
            "Incident Information",
            heading_style
        )
    )

    incident_data = [
        ["Incident ID", str(incident.id)],
        ["Title", incident.title],
        ["Severity", incident.severity],
        ["Risk Score", str(incident.risk_score)],
        ["Status", incident.status],
        ["Username", incident.username],
        ["Hostname", incident.hostname],
        ["Source IP", incident.source_ip],
        ["MITRE Technique", incident.mitre_technique],
        ["Created At", str(incident.created_at)]
    ]

    table = Table(
        incident_data,
        colWidths=[45 * mm, 120 * mm]
    )

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 6)
        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 20))

    # Analysis
    elements.append(
        Paragraph(
            "Security Analysis",
            heading_style
        )
    )

    analysis_text = (
        f"SentinelAI detected the incident "
        f"<b>{incident.title}</b> involving user "
        f"<b>{incident.username}</b> on host "
        f"<b>{incident.hostname}</b>. "
        f"The incident has been classified as "
        f"<b>{incident.severity}</b> with a risk score of "
        f"<b>{incident.risk_score}/100</b>."
    )

    elements.append(
        Paragraph(
            analysis_text,
            normal_style
        )
    )

    elements.append(Spacer(1, 12))

    mitre_text = (
        f"The detected activity was mapped to MITRE ATT&CK "
        f"technique <b>{incident.mitre_technique}</b>."
    )

    elements.append(
        Paragraph(
            mitre_text,
            normal_style
        )
    )

    elements.append(Spacer(1, 20))

    # Recommendations
    elements.append(
        Paragraph(
            "Recommended Actions",
            heading_style
        )
    )

    recommendations = [
        "Review the affected user account.",
        "Verify whether the activity was legitimate.",
        "Review related events from the source IP.",
        "Check the affected host for known vulnerabilities.",
        "Continue monitoring the affected asset."
    ]

    for recommendation in recommendations:

        elements.append(
            Paragraph(
                "• " + recommendation,
                normal_style
            )
        )

        elements.append(Spacer(1, 5))

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Generated by SentinelAI",
            normal_style
        )
    )

    doc.build(elements)